version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=KEY_HERE
      - WIREGUARD_ADDRESSES=IP_HERE
      - VPN_ENDPOINT_PORT=PORT_HERE
      - SERVER_CITIES=CITY_HERE
  
  hongerlive:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /YOUR_PATH:/arcalive
    network_mode: service:gluetun